# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glmt < Formula
  desc "GitLab merge request tool"
  homepage "https://github.com/sairus2k/glmt"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sairus2k/glmt/releases/download/v0.1.11/glmt_0.1.11_darwin_amd64.tar.gz"
      sha256 "d03542b9651a2dcb99c96a3c0c90cc51e12496ba1045e5cdebc8ddea7184d1fe"

      define_method(:install) do
        bin.install "glmt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sairus2k/glmt/releases/download/v0.1.11/glmt_0.1.11_darwin_arm64.tar.gz"
      sha256 "6df4e95e9d6592c0d5106da1828a47d1a13e205e1e34db897860057773e8c8e7"

      define_method(:install) do
        bin.install "glmt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sairus2k/glmt/releases/download/v0.1.11/glmt_0.1.11_linux_amd64.tar.gz"
      sha256 "62afe8aaab7441dbd861259d73b692efb33cb8838d1827711f673b3d14379619"
      define_method(:install) do
        bin.install "glmt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sairus2k/glmt/releases/download/v0.1.11/glmt_0.1.11_linux_arm64.tar.gz"
      sha256 "a87779ff8532a4233cbccf09b750f3efd134d50fd99381cda07d7ad0126d7ebb"
      define_method(:install) do
        bin.install "glmt"
      end
    end
  end
end
