# This file was generated by GoReleaser. DO NOT EDIT.
cask "glmt" do
  name "glmt"
  desc "GitLab merge request tool"
  homepage "https://github.com/sairus2k/glmt"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glmt"

  on_macos do
    on_intel do
      url "https://github.com/sairus2k/glmt/releases/download/v#{version}/glmt_#{version}_darwin_amd64.tar.gz"
      sha256 "5ac1047cf2991cdea6a1714826f2845b60a639701cd5e6167d325d9e20b28e53"
    end
    on_arm do
      url "https://github.com/sairus2k/glmt/releases/download/v#{version}/glmt_#{version}_darwin_arm64.tar.gz"
      sha256 "41dc6fd5b65c0bcc8e95807dcf487e88dd965004f15a05e1ed27710dd388ddc0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sairus2k/glmt/releases/download/v#{version}/glmt_#{version}_linux_amd64.tar.gz"
      sha256 "b0a859c902e32691d9b9ee0d2d38ce9eeb6170318e2e39ab7dcd9368c99035a1"
    end
    on_arm do
      url "https://github.com/sairus2k/glmt/releases/download/v#{version}/glmt_#{version}_linux_arm64.tar.gz"
      sha256 "73eb5ef1e9924cd0a1074299c26ef3224c45ef28d7a5806ddc64f05e4eee25da"
    end
  end

  # No zap stanza required
end
